apiVersion: v1
kind: Service
metadata:
  name: cert-manager-metrics
  namespace: cert-manager
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9402"
    prometheus.io/path: "/metrics"
  labels:
    app: cert-manager
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/instance: cert-manager
spec:
  type: ClusterIP
  ports:
  - port: 9402
    targetPort: 9402
    protocol: TCP
    name: metrics
  selector:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/instance: cert-manager
